REM   Script: Session 8
REM   19-04

SELECT D.DEPARTMENT_ID, E.DEPARTMENT_ID, E.LAST_NAME 
FROM HR.DEPARTMENTS D LEFT OUTER JOIN HR.EMPLOYEES E 
ON D.DEPARTMENT_ID = E.DEPARMENT_ID;

SELECT * FROM HR.EMPLOYEES;

SELECT * FROM HR.DEPARTMENTS;

SELECT D.DEPARTMENT_ID, E.DEPARTMENT_ID, E.LAST_NAME 
FROM HR.DEPARTMENTS D LEFT OUTER JOIN HR.EMPLOYEES E 
ON D.DEPARTMENT_ID = E.DEPARMENT_ID;

SELECT D.DEPARTMENT_ID, E.DEPARTMENT_ID, E.LAST_NAME 
FROM HR.DEPARTMENTS D LEFT OUTER JOIN HR.EMPLOYEES E 
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

SELECT D.DEPARTMENT_ID, E.DEPARTMENT_ID, E.LAST_NAME 
FROM HR.DEPARTMENTS D RIGHT OUTER JOIN HR.EMPLOYEES E 
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

SELECT D.DEPARTMENT_NAME, E.FIRST_NAME 
FROM HR.DEPARTMENTS D RIGHT OUTER HR.EMPLOYEES E 
ON D.MANAGER_ID = E.EMPLOYEES_ID;

SELECT D.DEPARTMENT_NAME, E.FIRST_NAME 
FROM HR.DEPARTMENTS D RIGHT OUTER JOIN HR.EMPLOYEES E 
ON D.MANAGER_ID = E.EMPLOYEE_ID;

SELECT D.DEPARTMENT_NAME, E.FIRST_NAME 
FROM HR.DEPARTMENTS D LEFT OUTER JOIN HR.EMPLOYEES E 
ON D.MANAGER_ID = E.EMPLOYEE_ID;

SELECT D.DEPARTMENT_NAME, E.FIRST_NAME 
FROM HR.DEPARTMENTS D RIGHT OUTER JOIN HR.EMPLOYEES E 
ON D.MANAGER_ID = E.EMPLOYEE_ID 
;

SELECT D.DEPARTMENT_NAME, E.FIRST_NAME 
FROM HR.DEPARTMENTS D RIGHT OUTER JOIN HR.EMPLOYEES E 
ON D.MANAGER_ID = E.EMPLOYEE_ID;

SELECT D.DEPARTMENT_NAME, E.FIRST_NAME 
FROM HR.DEPARTMENTS D FULL OUTER JOIN HR.EMPLOYEES E 
ON D.MANAGER_ID = E.EMPLOYEE_ID;

SELECT D.DEPARTMENT_ID, E.LAST_NAME 
FROM HR.DEPARTMENTS D, HR.EMPLOYEES E 
WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, C.CITY 
FROM HR.DEPARTMENTS D, HR.LOCATIONS C 
WHERE C.LOCATIONS_ID BETWEEN 1800 AND 2500;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, C.CITY 
FROM HR.DEPARTMENTS D, HR.LOCATIONS C 
WHERE C.LOCATION_ID BETWEEN 1800 AND 2500 AND D.DEPARTMENT_ID < 30;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, C.CITY 
FROM HR.DEPARTMENTS D, HR.LOCATIONS C 
WHERE C.LOCATION_ID BETWEEN 1800 AND 2500 AND D.DEPARTMENT_ID < 30;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, C.CITY 
FROM HR.DEPARTMENTS D INNER JOIN HR.LOCATIONS C 
ON C.LOCATION_ID BETWEEN 1800 AND 2500 AND D.DEPARTMENT_ID < 30;

SELECT L.POSRTAL_CODE, L.CITY, C.REGION_ID, C.OUNTRY_NAME 
FROM HR.LOCATIONS L 
NATURAL JOIN HR.COUNTRIES C;

SELECT L.POSRTAL_CODE, L.CITY, C.REGION_ID, C.COUNTRY_NAME 
FROM HR.LOCATIONS L 
NATURAL JOIN HR.COUNTRIES C;

SELECT L.POSTAL_CODE, L.CITY, C.REGION_ID, C.COUNTRY_NAME 
FROM HR.LOCATIONS L 
NATURAL JOIN HR.COUNTRIES C;

SELECT * FROM HR.EMPLOYEES;

SELECT E1.LAST_NAME|| 'TRABBALHA PARA ' || E2.LAST_NAME 
FROM HR.EMPLOYEES E1, HR.EMPLOYEES E2 
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID;

SELECT E1.LAST_NAME|| 'TRABBALHA PARA ' || E2.LAST_NAME 
FROM HR.EMPLOYEES E1, HR.EMPLOYEES E2 
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID;

SELECT E1.LAST_NAME|| ' TRABBALHA PARA ' || E2.LAST_NAME 
FROM HR.EMPLOYEES E1, HR.EMPLOYEES E2 
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID;

SELECT E1.LAST_NAME|| ' TRABBALHA PARA ' || E2.LAST_NAME "FUNCIONARIOS E SEUS GERENTES" 
FROM HR.EMPLOYEES E1, HR.EMPLOYEES E2 
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.DEPARTMENTS D 
WHERE EXISTS (SELECT 1 FROM HR.EMPLOYEES E 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) 
ORDER BY.DEPARTMENT_ID;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.DEPARTMENTS D 
WHERE EXISTS (SELECT 1 FROM HR.EMPLOYEES E 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) 
ORDER BY D.DEPARTMENT_ID;

SELECT * FROM HR.EMPLOYEES 
SELECT * FROM HR.DEPARTMENTS 
 
SELECT D.DEPARTMENT_ID, E.DEPARTMENT_ID, E.LAST_NAME 
FROM HR.DEPARTMENTS D RIGHT OUTER JOIN HR.EMPLOYEES E 
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

SELECT D.DEPARTMENT_NAME, E.FIRST_NAME 
FROM HR.DEPARTMENTS D LEFT OUTER JOIN HR.EMPLOYEES E 
ON D.MANAGER_ID = E.EMPLOYEE_ID 
 
SELECT D.DEPARTMENT_NAME, E.FIRST_NAME 
FROM HR.DEPARTMENTS D RIGHT OUTER JOIN HR.EMPLOYEES E 
ON D.MANAGER_ID = E.EMPLOYEE_ID 
 
SELECT D.DEPARTMENT_NAME, E.FIRST_NAME 
FROM HR.DEPARTMENTS D FULL OUTER JOIN HR.EMPLOYEES E 
ON D.MANAGER_ID = E.EMPLOYEE_ID 
 
 
-- EQUIJOIN(PRODUTO CARTESIANO) 
SELECT D.DEPARTMENT_ID, E.LAST_NAME 
FROM HR.DEPARTMENTS D, HR.EMPLOYEES E 
WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, C.CITY 
FROM HR.DEPARTMENTS D, HR.LOCATIONS C 
WHERE C.LOCATION_ID BETWEEN 1800 AND 2500 AND D.DEPARTMENT_ID < 30;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, C.CITY 
FROM HR.DEPARTMENTS D INNER JOIN HR.LOCATIONS C 
ON C.LOCATION_ID BETWEEN 1800 AND 2500 AND D.DEPARTMENT_ID < 30;

SELECT L.POSTAL_CODE, L.CITY, C.REGION_ID, C.COUNTRY_NAME 
FROM HR.LOCATIONS L 
NATURAL JOIN HR.COUNTRIES C;

SELECT L.POSTAL_CODE, L.CITY, C.REGION_ID, C.COUNTRY_NAME 
FROM HR.LOCATIONS L 
NATURAL JOIN HR.COUNTRIES C;

SELECT * FROM HR.EMPLOYEES;

SELECT * FROM HR.EMPLOYEES;

SELECT E1.LAST_NAME|| ' TRABBALHA PARA ' || E2.LAST_NAME "FUNCIONARIOS E SEUS GERENTES" 
FROM HR.EMPLOYEES E1, HR.EMPLOYEES E2 
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID;

SELECT E1.LAST_NAME|| ' TRABBALHA PARA ' || E2.LAST_NAME "FUNCIONARIOS E SEUS GERENTES" 
FROM HR.EMPLOYEES E1, HR.EMPLOYEES E2 
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.DEPARTMENTS D 
WHERE EXISTS (SELECT 1 FROM HR.EMPLOYEES E 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) 
ORDER BY D.DEPARTMENT_ID;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.DEPARTMENTSD, HR.EMPLOYEES E 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID 
ORDER BY D.DEPARTMENT_ID 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.DEPARTMENTS D 
WHERE EXISTS (SELECT 1 FROM HR.EMPLOYEES E 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) 
ORDER BY D.DEPARTMENT_ID;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.DEPARTMENTSD, HR.EMPLOYEES E 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID 
ORDER BY D.DEPARTMENT_ID 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.DEPARTMENTSD, HR.EMPLOYEES E 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID 
ORDER BY D.DEPARTMENT_ID 
;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.DEPARTMENTSD, HR.EMPLOYEES E 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID 
ORDER BY D.DEPARTMENT_ID 
;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.DEPARTMENT D, HR.EMPLOYEES E 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID 
ORDER BY D.DEPARTMENT_ID 
;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.DEPARTMENTS D 
WHERE EXISTS (SELECT 1 FROM HR.EMPLOYEES E 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) 
ORDER BY D.DEPARTMENT_ID;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.DEPARTMENTS D, HR.EMPLOYEES E 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID 
ORDER BY D.DEPARTMENT_ID;

SELECT DISTINCT D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.DEPARTMENTS D, HR.EMPLOYEES E 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID 
ORDER BY D.DEPARTMENT_ID;

SELECT D.MANAGER_ID, E.FIRST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.EMPLOYEES E, HR.DEPARTMENTS D 
WHERE E.EMPLOYEE_ID = D.MANAGER_ID;

SELECT D.MANAGER_ID, E.FIRST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.EMPLOYEES E LEFT OUTER JOIN HR.DEPARTMENTS D 
ON E.EMPLOYEE_ID = D.MANAGER_ID;

SELECT D.MANAGER_ID, E.FIRST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.EMPLOYEES E LEFT OUTER JOIN HR.DEPARTMENTS D 
ON E.EMPLOYEE_ID = D.MANAGER_ID;

SELECT D.MANAGER_ID, E.FIRST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM HR.EMPLOYEES E INNER JOIN HR.DEPARTMENTS D 
ON E.EMPLOYEE_ID = D.MANAGER_ID;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.EMPLOYEE_ID 
FROM EMPLOYEES E 
RIGHT JOIN DEPARTMENTS D 
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
WHERE E.DEPARTMENT_ID IS NULL;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.EMPLOYEE_ID 
FROM HR.EMPLOYEES E 
RIGHT JOIN HR.DEPARTMENTS D 
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
WHERE E.DEPARTMENT_ID IS NULL;

