--CRIAR TABELA
CREATE TABLE FUNCIONARIO(
    FUNC_ID INTEGER PRIMARY KEY NOT NULL,
    FUNC_NOME VARCHAR2(150) NOT NULL,
    FUNC_ENDERECO VARCHAR2(200) NOT NULL,
    FUNC_IDADE NUMBER NOT NULL
);
SELECT TABLE_NAME FROM USER_TABLES;
SELECT * FROM FUNCIONARIO;


--INSERIR DADOS
INSERT INTO FUNCIONARIO(NOME DAS COLUNAS)VALUES(VALORES);
INSERT INTO FUNCIONARIO VALUES(1,'FULANO DA SILVA','END 1',54);


--APAGAR TABELA
DROP TABLE FUNCIONARIO;


-- CRIANDO TABELAS TEMPORARIAS
CREATE GLOBAL TEMPORARY TABLE FUNCIONARIO(
    FUNC_ID INTEGER PRIMARY KEY NOT NULL,
    FUNC_NOME VARCHAR2(150) NOT NULL,
    FUNC_ENDERECO VARCHAR2(200) NOT NULL,
    FUNC_IDADE NUMBER NOT NULL
);
-- CREATE PRIVATE TEPORARY TABLE FUNCIONARIO


CREATE TABLE FUNCIONARIO(
    FUNC_ID INTEGER PRIMARY KEY NOT NULL,
    FUNC_NOME VARCHAR2(150) NOT NULL,
    FUNC_ENDERECO VARCHAR2(200) NOT NULL
);


-- ALTERANDO TABELAS
ALTER TABLE FUNCIONARIO ADD(IDADE NUMBER);
ALTER TABLE FUNCIONARIO ADD(CIDADE VARCHAR2(200) NOT NULL,
                            UF VARCHAR2(2) NOT NULL,
                            TELEFONE VARCHAR2(9) NOT NULL
);


-- RENOMEANDO CAMPOS
ALTER TABLE FUNCIONARIO RENAME COLUMN IDADE TO FUNC_IDADE;


-- APAGAR COLUNADS DA TABELA
ALTER TABLE FUNCIONARIO DROP(TELEFONE);


-- RELACIONANDO TABELAS
CREATE TABLE MARCA(
    ID_MARCA INTEGER NOT NULL,
    MARCA VARCHAR2(15),
    CONSTRAINT MARCA_ID_PK PRIMARY KEY(ID_MARCA)
);


-- RELACIONAMENTOM COM A  TABELA MARCA
CREATE TABLE CARRO(
    ID_CARRO INTEGER NOT NULL,
    ID_MARCA INTEGER NOT NULL,
    MODELO VARCHAR2(120),
    COR VARCHAR2(20),
    PLACA VARCHAR2(80) NOT NULL,
    CONSTRAINT MARCA_ID_FK FOREIGN KEY(ID_MARCA) REFERENCES MARCA(ID_MARCA)
);
